USE [SQLI2]
GO
/****** Object:  User [SQLi2]    Script Date: 12/23/2015 1:07:16 AM ******/
CREATE USER [SQLi2] FOR LOGIN [SQLi2] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[T_SURVEY]    Script Date: 12/23/2015 1:07:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[T_SURVEY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](20) NOT NULL,
	[RATING] [tinyint] NOT NULL,
	[FAVORITE] [varchar](max) NOT NULL,
	[LEAST] [varchar](max) NOT NULL,
	[OFFICER] [varchar](20) NOT NULL,
	[WHY] [varchar](max) NOT NULL,
	[DATE_INSERTED] [datetime] NOT NULL CONSTRAINT [DF_T_SURVEY_DATE_INSERTED]  DEFAULT (getdate()),
 CONSTRAINT [PK_T_SURVERY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
